/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_bibliotheque;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import static sun.net.www.http.HttpClient.New;

/**
 *
 * @author nianacoro
 */
public class Catalogue extends javax.swing.JFrame {

  
    public Catalogue() {
        initComponents();
        this.Liste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAcceuil = new javax.swing.JMenu();
        jMenuAchat = new javax.swing.JMenu();
        jMenuPret = new javax.swing.JMenu();
        jMenuRetour = new javax.swing.JMenu();
        jMenuInscription = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTE DES OUVRAGES");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jList1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jList1);

        jMenuAcceuil.setText("Acceuil");
        jMenuAcceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAcceuilMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAcceuil);

        jMenuAchat.setText("Achat");
        jMenuAchat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAchatMouseClicked(evt);
            }
        });
        jMenuAchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAchatActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuAchat);

        jMenuPret.setText("Pret");
        jMenuPret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPretMouseClicked(evt);
            }
        });
        jMenuPret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPretActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuPret);

        jMenuRetour.setText("Retour");
        jMenuRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRetourMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRetour);

        jMenuInscription.setText("Inscription");
        jMenuInscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInscriptionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuInscription);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAchatActionPerformed
         // SERVICE ACHAT
        this.dispose();
       // Achat achat = new Achat();
       // achat.setVisible(true);
    }//GEN-LAST:event_jMenuAchatActionPerformed

    private void jMenuPretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPretActionPerformed

          // SERVICE PRET
        this.dispose();
      // Pret pret = new Pret();
      //  pret.setVisible(true);
    }//GEN-LAST:event_jMenuPretActionPerformed

    private void jMenuRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRetourMouseClicked
         // SERVICE Accueil
        this.dispose();
        Accueil acceuil = new Accueil();
        acceuil.setVisible(true);
    }//GEN-LAST:event_jMenuRetourMouseClicked

    private void jMenuInscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInscriptionMouseClicked
         // SERVICE INSCRIPTION
        this.dispose();
        Inscription inscription = new Inscription();
       inscription.setVisible(true);
    }//GEN-LAST:event_jMenuInscriptionMouseClicked

    private void jList1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jList1AncestorAdded
      
    }//GEN-LAST:event_jList1AncestorAdded

    private void jMenuAcceuilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAcceuilMouseClicked
         // menu Accueil
        Accueil accueil = new Accueil();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuAcceuilMouseClicked

    private void jMenuAchatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAchatMouseClicked
       // menu Achat
        Achat achat = new Achat();
        achat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuAchatMouseClicked

    private void jMenuPretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPretMouseClicked
         // menu Pret
        Pret Pret = new Pret();
        Pret.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPretMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
       /*try {
            // TODO code application logic here
            
            
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        String url = "jdbc:mysql://localhost:3306/projet_bibliotheque";
        String user = "root";
        String mdp = "";
        Connection cnt = DriverManager.getConnection(url,user,mdp);
        Statement stt = cnt.createStatement();
        ResultSet rs = stt.executeQuery("SELECT * FROM ouvrage");
        while(rs.next()){
            String auteur = rs.getString("auteur");
            String titre = rs.getString("titre");
            String prix = rs.getString("prix");
            String resume = rs.getString("resume");
            String motclefs = rs.getString("motsclefs");
            
            //DefaultListModel dlm=new DefaultListModel();
            //System.out.println("auteur:"+auteur+"|"+titre+"|"+prix+"|"+resume+"|"+motclefs);
           //System.out.((DefaultListModel)JList.getModel()).add(auteur) ;
        }
        
        stt.close();
        cnt.close();*/
           
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogue().setVisible(true);
            }
        });
    }
    
    public void Liste(){ 
          
        int i;
        String resultat = "";
        Statement stt = null;
        try {
                String url = "jdbc:mysql://localhost:3306/projet_bibliotheque";
                String user = "root";
                String mdp = "";
                
                
                Connection cnt = DriverManager.getConnection(url,user,mdp);
                
                 //Préparer la requette 
            PreparedStatement ps=cnt.prepareStatement("SELECT * FROM `ouvrage`");
            
            ResultSet rs=ps.executeQuery();
            
            ResultSetMetaData rsmd=rs.getMetaData();
            
            DefaultListModel<String> liste = new DefaultListModel<>();
           
            while(rs.next()){
                liste.addElement(rs.getString("Titre")+" , "+ rs.getString("Auteur"));

            }
            
            jList1.setModel(liste);

 
            rs.close();
            ps.close();
            cnt.close();
            
        }catch(Exception e){
            e.printStackTrace();
        }
           

    }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenuAcceuil;
    private javax.swing.JMenu jMenuAchat;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInscription;
    private javax.swing.JMenu jMenuPret;
    private javax.swing.JMenu jMenuRetour;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
