/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_bibliotheque;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author nianacoro
 */
public class Pret2 extends javax.swing.JFrame {

    /**
     * Creates new form Pret2
     */
    public Pret2() {
        initComponents();
        ListeOuvrage();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonAjouter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButtonVider = new javax.swing.JButton();
        jTextFcarte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAcceuil = new javax.swing.JMenu();
        JMenuAchat = new javax.swing.JMenu();
        jMenuPret = new javax.swing.JMenu();
        jMenuRetour = new javax.swing.JMenu();
        jMenuInscription = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("LISTE DES OUVRAGES");

        jButtonAjouter.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonAjouter.setText("AJOUTER");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jButtonVider.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonVider.setText("VIDER");
        jButtonVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViderActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("NUMERO DE CARTE");

        jButtonValider.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonValider.setText("VALIDER");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("LISTE DES SELECTIONS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("EMPRUNT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jMenuAcceuil.setText("Acceuil");
        jMenuAcceuil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAcceuilMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAcceuil);

        JMenuAchat.setText("Achat");
        JMenuAchat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuAchatMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMenuAchat);

        jMenuPret.setText("Pret");
        jMenuPret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPretMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPret);

        jMenuRetour.setText("Retour");
        jMenuRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRetourMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRetour);

        jMenuInscription.setText("Inscription");
        jMenuInscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInscriptionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuInscription);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFcarte, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(301, 301, 301))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVider, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(303, 303, 303))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(288, 288, 288))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFcarte))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonVider, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButtonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        //ajouter des ouvrages liste 
        int[] selected = jList1.getSelectedIndices();

        DefaultListModel ls1 = new DefaultListModel();
        ListModel list = jList2.getModel();

        for (int i = 0; i < list.getSize(); i++) {
            Object prev = list.getElementAt(i);
            ls1.addElement(prev);
        }

        for (int i = 0; i < selected.length; i++) {
            Object ls2 = jList1.getModel().getElementAt(selected[i]);
            ls1.addElement(ls2);
          }

        jList2.setModel(ls1);

        if(jList2.getLastVisibleIndex()>2){
            JOptionPane.showMessageDialog(null, " Vous  pouvez emprunter au maximum 3 ouvrages !", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        String jtx = jTextFcarte.getText();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        Date semaines = new Date(date.getTime() + (1000 * 60 * 60 * 504));
        
        
        
         if(jtx.isEmpty() ){JOptionPane.showMessageDialog(null, "Veuiller mettre votre numero de carte!");}
    else{
        try{
             //chargement du pilote
            Class.forName("com.mysql.jdbc.Driver");
            //Creer la connection
            Connection conn = DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/projet_bibliotheque", "root", "");
            
                  /*ListModel liste2 = jList2.getModel();
                 for(int i = 0; i < liste2.getSize(); i++){
                     String selected = jList2.getSelectedValue();
                  String  cdbE =  selected.substring(0,1);
                  //System.out.println("cest :"+cdbE);
                 }*/
                /*for(int i = 0; i < liste2.getSize(); i++){
                    Object obj = liste2.getElementAt(i);
                   // System.out.println("cest :"+obj);
                   String ele = jList2.getSelectedIndices().toString();
                   String fin=  ele.substring(0,2);
                 System.out.println("cest :"+fin);  
                }*/
                
                
            
             //Préparer la requette 
            PreparedStatement ps =conn.prepareStatement("INSERT INTO emprunt (CodeBarreExemplaire,CodeBarreEmprunteur,DateRetourMax,DateRetour) VALUES (?,?,?,?)");
            ps.setObject(1,jList2.getSelectedValue().substring(0,1));
            ps.setObject(2,jTextFcarte.getText());
            ps.setObject(3,dateFormat.format(semaines));
            ps.setObject(4,dateFormat.format(semaines));
            
            //ps.executeUpdate();
            
             if(ps.executeUpdate()!=1){
			    	JOptionPane.showMessageDialog(null, "une erreur est apparu lors de l'emprunt !", 
                            "Error Message",
                            JOptionPane.ERROR_MESSAGE);}
			    else{JOptionPane.showMessageDialog(null, "L'emprunt  à bien ete valide !", 
                        "Information Message",
                        JOptionPane.INFORMATION_MESSAGE);}
            
           
            conn.close();
            ps.close();
        }catch(Exception e){
            //System.out.println();
            
            //JOptionPane.showMessageDialog(null, e);
        }
    }       
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViderActionPerformed
         //bouton vide
        DefaultListModel lm = new DefaultListModel();
                lm.addElement("");
                    jList2.setModel(lm);
    }//GEN-LAST:event_jButtonViderActionPerformed

    private void JMenuAchatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuAchatMouseClicked
      // menu Achat
        Achat achat = new Achat();
        achat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JMenuAchatMouseClicked

    private void jMenuPretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPretMouseClicked
         // menu Pret
        Pret pret = new Pret();
        pret.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuPretMouseClicked

    private void jMenuRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRetourMouseClicked
         // menu retour
        Retour retour = new Retour();
        retour.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuRetourMouseClicked

    private void jMenuInscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInscriptionMouseClicked
        // menu Inscription
        Inscription inscription = new Inscription();
        inscription.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuInscriptionMouseClicked

    private void jMenuAcceuilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAcceuilMouseClicked
         // menu Accueil
        Accueil accueil = new Accueil();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuAcceuilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pret2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pret2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pret2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pret2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pret2().setVisible(true);
            }
        });
    }
    public void ListeOuvrage(){ 
          
        int i;
        String resultat = "";
        Statement stt = null;
        try {
                String url = "jdbc:mysql://localhost:3306/projet_bibliotheque";
                String user = "root";
                String mdp = "";
                
                
                Connection cnt = DriverManager.getConnection(url,user,mdp);
                
                 //Préparer la requette 
            PreparedStatement ps=cnt.prepareStatement("SELECT * FROM `ouvrage`");
            
            ResultSet rs=ps.executeQuery();
            
            ResultSetMetaData rsmd=rs.getMetaData();
            
            DefaultListModel<String> liste = new DefaultListModel<>();
           
            while(rs.next()){
                liste.addElement(rs.getString("codebarre")+","+rs.getString("Titre")+" , "+ rs.getString("Auteur"));

            }
            
            jList1.setModel(liste);

 
            rs.close();
            ps.close();
            cnt.close();
            
        }catch(Exception e){
            e.printStackTrace();
        }
           

    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAchat;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JButton jButtonVider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenuAcceuil;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInscription;
    private javax.swing.JMenu jMenuPret;
    private javax.swing.JMenu jMenuRetour;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFcarte;
    // End of variables declaration//GEN-END:variables
}
