/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projet_bibliotheque;

/**
 *
 * @author svenm
 */

import javax.swing.*;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;


public class Retour extends javax.swing.JFrame {

    /** Creates new form Retour */
    public Retour() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputCodeOuvrage = new javax.swing.JSpinner();
        inputCodeEmprunteur = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAccueil = new javax.swing.JMenu();
        jMenuAchat = new javax.swing.JMenu();
        jMenuPret = new javax.swing.JMenu();
        jMenuRetour = new javax.swing.JMenu();
        jMenuInscription = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Service Retour");

        jLabel2.setText("Code barre ouvrage :");

        jLabel3.setText("Code barre Emprunteur :");

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuAccueil.setText("Accueil");
        jMenuAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAccueilMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAccueil);

        jMenuAchat.setText("Achat");
        jMenuAchat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAchatMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAchat);

        jMenuPret.setText("Pret");
        jMenuPret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPretMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPret);

        jMenuRetour.setText("Retour");
        jMenuRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRetourMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuRetour);

        jMenuInscription.setText("Inscription");
        jMenuInscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInscriptionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuInscription);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(inputCodeEmprunteur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(inputCodeOuvrage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(246, 246, 246)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel2))
                .addContainerGap(337, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton1)
                .add(331, 331, 331))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inputCodeOuvrage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(39, 39, 39)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inputCodeEmprunteur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32)
                .add(jButton1)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.retourOuvrage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuAccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAccueilMouseClicked
        // Accueil
        Accueil accueil = new Accueil();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuAccueilMouseClicked

    private void jMenuAchatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAchatMouseClicked
        // SERVICE ACHAT
        this.dispose();
        Achat achat = new Achat();
        achat.setVisible(true);
    }//GEN-LAST:event_jMenuAchatMouseClicked

    private void jMenuPretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPretMouseClicked
        // SERVICE PRET
        this.dispose();
       Pret pret = new Pret();
       pret.setVisible(true);
    }//GEN-LAST:event_jMenuPretMouseClicked

    private void jMenuRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRetourMouseClicked
        // SERVICE RETOUR
        this.dispose();
        Retour retour = new Retour();
        retour.setVisible(true);
    }//GEN-LAST:event_jMenuRetourMouseClicked

    private void jMenuInscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInscriptionMouseClicked
        // SERVICE INSCRIPTION
        Inscription inscription = new Inscription();
        inscription.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuInscriptionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner inputCodeEmprunteur;
    private javax.swing.JSpinner inputCodeOuvrage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenuAccueil;
    private javax.swing.JMenu jMenuAchat;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInscription;
    private javax.swing.JMenu jMenuPret;
    private javax.swing.JMenu jMenuRetour;
    // End of variables declaration//GEN-END:variables

    
    
    public void retourOuvrage(){
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
    
        try{
            //chargement du pilote
            Class.forName("com.mysql.jdbc.Driver");
            //Creer la connection
            Connection conn = DriverManager.getConnection
                    ("jdbc:mysql://localhost:3306/projet_bibliotheque", "root", "");
            
            PreparedStatement ps = conn.prepareStatement("UPDATE emprunt SET DateRetour = '"+dateFormat.format(date)+"'  WHERE CodeBarreExemplaire = '"+this.inputCodeEmprunteur.getValue()+"' AND  CodeBarreEmprunteur = '"+this.inputCodeOuvrage.getValue()+"'");

            if(ps.executeUpdate()!=1){
			    	JOptionPane.showMessageDialog(null, "une erreur est apparu lors du retour !", 
                            "Error Message",
                            JOptionPane.ERROR_MESSAGE);}
			    else{JOptionPane.showMessageDialog(null, "Le retour a bien ete valide !", 
                        "Information Message",
                        JOptionPane.INFORMATION_MESSAGE);}

            conn.close();
            
            this.inputCodeEmprunteur.setValue(0);
            this.inputCodeOuvrage.setValue(0);
            
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Une erreur est apparu lors du retour !", 
                        "Information Message",
                        JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
